return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      indent = { enable = false },
      ensure_installed = {
        "go",
        "gomod",
        "gowork",
        "gosum",
        "bash",
        "html",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "vim",
        "yaml",
        "java",
        "css",
        "javascript",
        "jsdoc",
        "svelte",
        "tsx",
        "typescript",
        "http",
        "graphql",
      },
    },
  },
}
